
# Metodología de Actualización {#sec-metodologia}

<iframe src="assets/metodologia.html" width="100%" height="600px" style="border:none;"></iframe>


## Cálculo de Indicadores {#sec-metodologia-calculo}
### Tipos de variables utilizadas {#sec-metodologia-calculo-tipos}
### Estructura del cálculo {#sec-metodologia-calculo-estructura}
### Consideraciones técnicas {#sec-metodologia-calculo-consideraciones}
### Ejemplo aplicado {#sec-metodologia-calculo-ejemplo}

## Normalización {#sec-metodologia-normalizacion}
### Objetivo de la normalización {#sec-metodologia-normalizacion-objetivo}
### Criterios de la normalización {#sec-metodologia-normalizacion-criterios}
### Método utilizado {#sec-metodologia-normalizacion-metodo}
### Consideraciones metodológicas {#sec-metodologia-normalizacion-consideraciones}
### Ejemplo aplicado {#sec-metodologia-normalizacion-ejemplo}

## Ponderación {#sec-metodologia-ponderacion}
### Objetivo de la ponderación {#sec-metodologia-ponderacion-objetivo}
### Criterios de ponderación {#sec-metodologia-ponderacion-criterios}
### Métodos utilizados {#sec-metodologia-ponderacion-metodos}
### Consideraciones metodológicas {#sec-metodologia-ponderacion-consideraciones}
### Ejemplo aplicado {#sec-metodologia-ponderacion-ejemplo}

## Protocolos de Control de Calidad (QA/QC) {#sec-metodologia-qa}
### Objetivos del control de calidad {#sec-metodologia-qa-objetivos}
### Protocolos QA/QC aplicados {#sec-metodologia-qa-protocolos}
### Herramientas utilizadas {#sec-metodologia-qa-herramientas}
### Ejemplo aplicado {#sec-metodologia-qa-ejemplo}

## Validación Cruzada {#sec-metodologia-validacion}
### Objetivos de la validación cruzada {#sec-metodologia-validacion-objetivos}
### Tipos de validación cruzada {#sec-metodologia-validacion-tipos}
### Procedimientos aplicados {#sec-metodologia-validacion-procedimientos}
### Resultados esperados {#sec-metodologia-validacion-resultados}
### Ejemplo aplicado {#sec-metodologia-validacion-ejemplo}

## Georreferenciación {#sec-metodologia-georef}
### Objetivos de la georreferenciación {#sec-metodologia-georef-objetivos}
### Unidades espaciales utilizadas {#sec-metodologia-georef-unidades}
### Sistemas de referencia y formatos {#sec-metodologia-georef-sistemas}
### Fuentes de datos georreferenciados {#sec-metodologia-georef-fuentes}
### Procedimientos aplicados {#sec-metodologia-georef-procedimientos}
### Resultados esperados {#sec-metodologia-georef-resultados}
### Ejemplo aplicado {#sec-metodologia-georef-ejemplo}